# locales/ko.py — 한국어
STRINGS = {
    "app_title": "노래 합성 Lab 정렬 도구 - SVS Lab Aligner",
    "app_subtitle": "MFA 자동 레이블링  ·  피치 추출  ·  프로젝트 파일 생성",
    "system_ready": "✓ 시스템 준비 완료",
    "system_not_ready": "⚠ 설정 필요",
    "footer_text": "SVS Lab Aligner  •  PyWORLD + MFA + PySide6",
    "language": "언어",
    "single_file_processing": "📁 단일 파일 처리",
    "github_link": "🔗 GitHub 프로젝트",
    "check_status": "🔄 상태 확인",
    "audio_file": "오디오 파일",
    "drop_audio_hint": "드래그 앤 드롭 또는 클릭하여 오디오 파일 선택",
    "audio_formats_tip": "WAV / MP3 / FLAC / M4A / AAC 지원  •  최대 512 MB",
    "browse": "파일 선택…",
    "clear": "지우기",
    "aligner_backend": "정렬 백엔드",
    "backend_mfa_desc": "🎯 MFA：Kaldi 기반 음소 수준 강제 정렬. 정확도 높음, MFA 및 언어 모델 사전 설치 필요. 참조 텍스트 필수.",
    "backend_whisperx_desc": "🤖 WhisperX：Whisper ASR + wav2vec2 강제 정렬. 사전 모델 설치 불필요. 텍스트 선택 사항.",
    "backend_qwen3_asr_desc": "🌐 Qwen3-ASR-1.7B：중국어 억양에 더 강건함. 텍스트 선택 사항.",
    "backend_qwen3_aligner_desc": "📌 Qwen3-ForcedAligner-0.6B：노래용으로 설계된 경량 신경망 강제 정렬. 참조 텍스트 필수.",
    "aligner_device": "정렬 실행 장치",
    "device_auto": "자동 (GPU 우선)",
    "device_cpu": "CPU",
    "device_cuda": "CUDA (GPU)",
    "whisperx_gpu_hint": "GPU 정밀도 자동 선택: Turing/RTX 20xx+ → float16, Pascal/구형 → int8",
    "qwen3_gpu_hint": "Qwen3 GPU: Ampere → bfloat16; Pascal/Volta/Turing → float16; CPU → float32",
    "cpu_mode_hint": "⚠ CPU 모드는 느립니다. GPU가 없거나 VRAM이 부족할 때만 선택하세요",
    "auto_device_hint": "자동 감지: CUDA 장치가 있으면 GPU 우선, 정밀도는 아키텍처에 따라 자동 선택",
    "lab_midi_file": "LAB / MIDI 파일",
    "drop_lab_hint": "드래그 앤 드롭 또는 클릭하여 파일 1개 선택 (LAB 또는 MIDI)",
    "lab_midi_tip": "파일 1개만 허용: .lab 음소 주석  또는  .mid / .midi MIDI 파일",
    "input_text": "텍스트 입력",
    "text_placeholder_optional": "(선택) 비워두면 자동 전사, 또는 참조 텍스트를 붙여넣어 정확도 향상",
    "text_placeholder_required": "참조 텍스트를 여기에 붙여넣으세요",
    "text_optional_hint": "✓ ASR 모드 지원 — 텍스트 없이도 처리 가능",
    "char_count": "글자 수: {count}",
    "language_select": "언어",
    "lang_cmn": "보통화 🇨🇳",
    "lang_eng": "영어 🇬🇧",
    "lang_jpn": "일본어 🇯🇵",
    "lang_kor": "한국어 🇰🇷",
    "lang_yue": "광동어 🇭🇰",
    "processing_mode": "처리 모드",
    "mode_mfa_only": "레이블링만 (빠름)",
    "mode_full": "전체 처리 (레이블링 + F0 + 프로젝트)",
    "mode_project_only": "프로젝트만 (WAV + LAB / MIDI)",
    "mode_mfa_only_desc": "자동 정렬만 수행 — LAB 파일 생성",
    "mode_full_desc": "전체 파이프라인: 정렬 → F0 추출 → 프로젝트 파일 생성",
    "mode_project_only_desc": "기존 WAV와 LAB/MIDI 파일을 통합하여 프로젝트 생성. 정렬 건너뜀",
    "output_format": "출력 형식",
    "format_sv": "Synthesizer V Studio (.svp)",
    "format_utau": "OpenUtau / UTAU (.ustx)",
    "phoneme_conversion": "음소 변환",
    "phoneme_none": "변환 없음",
    "phoneme_merge": "자음 병합",
    "phoneme_hiragana": "히라가나",
    "phoneme_katakana": "가타카나",
    "phoneme_none_desc": "LAB의 원래 음소 레이블 그대로 유지 (모든 언어 적용)",
    "phoneme_merge_desc": "자음과 모음을 합쳐 로마자 음절로 변환 (s+a→sa, N→N)",
    "phoneme_hiragana_desc": "자음+모음 병합 후 히라가나로 변환 (s+a→さ, N→ん)",
    "phoneme_katakana_desc": "자음+모음 병합 후 가타카나로 변환 (s+a→サ, N→ン)",
    "phoneme_warning": "⚠ 병합/가나 변환은 개별 음소가 있는 일본어 LAB 파일(MFA 원본 출력)에 사용하세요",
    "track_name": "트랙 이름",
    "track_name_placeholder": "트랙 이름 입력",
    "advanced_settings": "⚙️  고급 설정",
    "advanced_hide": "⚙️  고급 설정 닫기",
    "bpm": "BPM (박자/분)",
    "base_pitch": "기준 음높이 (MIDI 노트)",
    "pitch_control": "📈  피치 세부 조정",
    "auto_note_pitch": "자동 노트 피치",
    "auto_note_pitch_on": "실제 피치에 자동 정렬",
    "auto_note_pitch_off": "기준 음높이 고정",
    "export_pitch_line": "연속 피치 내보내기",
    "export_pitch_line_on": "F0 곡선 파라미터 기록",
    "export_pitch_line_off": "클린 노트만 생성",
    "f0_method_section": "F0 추출 알고리즘 및 범위",
    "f0_method": "F0 추출 방법",
    "f0_dio": "DIO  (빠름)",
    "f0_harvest": "Harvest  (정확)",
    "f0_crepe": "CREPE  (신경망, 노이즈 강건)",
    "f0_rmvpe": "RMVPE  (딥모델, 가장 강건)",
    "crepe_model_size": "CREPE 모델 크기",
    "crepe_full": "Full  (높은 정확도)",
    "crepe_tiny": "Tiny  (빠른 처리)",
    "f0_device": "실행 장치",
    "precision": "부동소수점 정밀도",
    "precision_single": "단정밀도  (Float32)",
    "precision_double": "배정밀도  (Float64)",
    "f0_smooth": "F0 스무딩",
    "f0_smooth_window": "스무딩 윈도우 크기",
    "f0_floor_hz": "최저 주파수 (Hz)",
    "f0_ceil_hz": "최고 주파수 (Hz)",
    "midi_lock_tip": "🔒 MIDI에서 읽기",
    "smooth_tip": "권장값: 3-7 (클수록 더 부드러움)",
    "f0_range_tip": "여성 보통 150-300 Hz  •  남성 80-150 Hz",
    "midi_loaded_banner": "🔒 MIDI 가져오기 완료 — 아래 옵션은 MIDI 데이터로 제어됩니다",
    "midi_lock_desc": "🔒 자동 노트 피치 · BPM · 기준 음높이 — MIDI 파일에서 직접 읽음",
    "bpm_from_midi": "🔒 {bpm} BPM  (MIDI에서)",
    "start_processing": "🚀  처리 시작",
    "processing_btn": "처리 중…  {percent}%",
    "reset": "🔄  초기화",
    "system_not_ready_hint": "(시스템 미준비 또는 언어 모델 미다운로드)",
    "result_title": "✅  처리 결과",
    "processing_time": "처리 시간: {time}",
    "lab_file_label": "LAB 파일: {name}",
    "project_file_label": "프로젝트 파일: {name}",
    "segments_label": "세그먼트 수: {count}",
    "tab_lab_content": "LAB 주석",
    "tab_file_info": "파일 정보",
    "tab_details": "처리 상세",
    "copy_lab": "📋  LAB 복사",
    "download_lab": "📥  LAB 다운로드",
    "download_project": "📥  프로젝트 다운로드",
    "process_next": "🔄  다음 파일 처리",
    "col_stage": "처리 단계",
    "col_status": "상태",
    "col_details": "상세",
    "stage_alignment": "1. 정렬",
    "stage_f0": "2. F0 추출",
    "stage_project": "3. 프로젝트 생성",
    "status_waiting": "대기 중",
    "status_running": "실행 중",
    "status_done": "완료",
    "status_skipped": "건너뜀",
    "status_failed": "실패",
    "lab_path_label": "LAB 주석 파일:",
    "project_path_label": "프로젝트 파일:",
    "output_format_label": "출력 형식:",
    "config_label": "처리 구성:",
    "cfg_bpm": "BPM: {v}",
    "cfg_base_pitch": "기준 음높이: {note}  (MIDI {midi})",
    "cfg_auto_pitch": "자동 노트 피치: {state}",
    "cfg_export_pitch": "연속 피치 내보내기: {state}",
    "cfg_f0_method": "F0 방법: {method}",
    "cfg_device": "실행 장치: {device}",
    "cfg_precision": "정밀도: {prec}",
    "state_on": "활성화",
    "state_off": "비활성화",
    "sv_studio": "Synthesizer V Studio",
    "openutau": "OpenUtau / UTAU",
    "system_status": "🔧  시스템 상태",
    "mfa_status": "MFA 상태:",
    "mfa_installed": "✓ 설치됨",
    "mfa_not_installed": "✗ 미설치",
    "mfa_version": "버전:",
    "language_models": "언어 모델:",
    "processing_modules": "처리 모듈:",
    "alt_backends_section": "대체 정렬 백엔드:",
    "model_cache_dir": "📁 모델 캐시:",
    "download_btn": "다운로드",
    "downloading_btn": "다운로드 중…",
    "model_cmn": "CMN  (보통화)",
    "model_eng": "ENG  (영어)",
    "model_jpn": "JPN  (일본어)",
    "model_kor": "KOR  (한국어)",
    "model_yue": "YUE  (광동어)",
    "warn_mfa_not_installed": "❌  MFA가 설치되지 않았습니다",
    "warn_mfa_install_cmd": "pip install montreal-forced-aligner",
    "warn_not_ready_title": "⚠️  컴포넌트 미준비",
    "warn_not_ready_msg": "필요한 언어 모델을 다운로드하거나 시스템 상태를 확인하세요.",
    "warn_install_hint": "그런 다음 필요한 언어 모델을 다운로드하세요.",
    "msg_only_one_file": "파일은 1개만 업로드할 수 있습니다",
    "msg_invalid_lab_type": ".lab / .mid / .midi 파일만 지원됩니다",
    "msg_no_lab_content": "다운로드할 LAB 내용이 없습니다",
    "msg_copied": "클립보드에 복사되었습니다",
    "msg_copy_failed": "복사에 실패했습니다",
    "msg_model_ok": "모델 '{lang}'이(가) 성공적으로 다운로드되었습니다",
    "msg_model_fail": "모델 다운로드 실패: {error}",
    "msg_backend_unreachable": "백엔드에 연결할 수 없습니다",
    "msg_processing_ok": "✅  처리가 완료되었습니다!",
    "msg_project_ok": "✅  프로젝트 파일이 생성되었습니다!",
    "msg_status_refreshed": "시스템 상태가 갱신되었습니다",
    "msg_select_audio": "오디오 파일을 선택해 주세요",
    "msg_select_lab_midi": "LAB 또는 MIDI 파일을 선택해 주세요",
    "msg_enter_text": "텍스트를 입력해 주세요 (MFA / Qwen3-FA 모드는 참조 텍스트가 필요합니다)",
    "msg_backend_not_ready": "정렬 백엔드가 준비되지 않았습니다. 시스템 상태를 확인하세요",
    "msg_audio_too_large": "오디오 파일이 512 MB를 초과합니다. 분할을 권장합니다",
    "msg_lab_downloaded": "LAB 파일이 다운로드되었습니다: {name}",
    "install_whisperx": "pip install whisperx",
    "install_qwen3": "pip install transformers torch torchaudio accelerate",
    "need_install": "설치 필요",
    "status_available": "사용 가능",
    "backend_url_label": "백엔드 URL:",
    "backend_url_placeholder": "http://127.0.0.1:5000",
    "connect": "연결",
}
