# locales/zh_cn.py — 简体中文
STRINGS = {
    "app_title": "歌声合成 Lab 标注工具 - SVS Lab Aligner",
    "app_subtitle": "MFA自动标注  ·  音高提取  ·  工程文件生成",
    "system_ready": "✓ 系统就绪",
    "system_not_ready": "⚠ 需要配置",
    "footer_text": "SVS Lab Aligner  •  PyWORLD + MFA + PySide6",
    "language": "界面语言",

    "single_file_processing": "📁 单文件处理",
    "github_link": "🔗 GitHub 项目链接",
    "check_status": "🔄 检查状态",

    "audio_file": "音频文件",
    "drop_audio_hint": "拖拽或点击选择音频文件",
    "audio_formats_tip": "支持 WAV / MP3 / FLAC / M4A / AAC  •  最大 512 MB",
    "browse": "选择文件…",
    "clear": "清除",

    "aligner_backend": "对齐后端",
    "backend_mfa_desc": "🎯 MFA：基于 Kaldi 的音素级强制对齐，精度高但需要提前安装 MFA 及语言模型。需要参考文本。",
    "backend_whisperx_desc": "🤖 WhisperX：Whisper ASR + wav2vec2 强制对齐，无需预先安装语言模型。文本可选。",
    "backend_qwen3_asr_desc": "🌐 Qwen3-ASR-1.7B：对中文多口音更鲁棒。文本可选。",
    "backend_qwen3_aligner_desc": "📌 Qwen3-ForcedAligner-0.6B：轻量级神经网络强制对齐，专为歌声设计。需要参考文本。",

    "aligner_device": "对齐运行设备",
    "device_auto": "自动 (优先 GPU)",
    "device_cpu": "CPU",
    "device_cuda": "CUDA (GPU)",
    "whisperx_gpu_hint": "GPU 精度根据显卡架构自动调整：Turing/RTX 20xx+ → float16，Pascal/旧卡 → int8",
    "qwen3_gpu_hint": "Qwen3 (GPU)：Ampere → bfloat16；Pascal/Volta/Turing → float16；CPU → float32",
    "cpu_mode_hint": "⚠️ CPU 模式下速度较慢，建议仅在无 GPU 或显存不足时选择",
    "auto_device_hint": "自动检测：有 CUDA 设备则优先使用 GPU，精度根据显卡架构自动选择",

    "lab_midi_file": "LAB / MIDI 文件",
    "drop_lab_hint": "拖拽或点击选择一个文件（LAB 或 MIDI）",
    "lab_midi_tip": "只允许导入一个文件：.lab 音素标注  或  .mid / .midi MIDI 音符 / BPM 来源",

    "input_text": "输入文本",
    "text_placeholder_optional": "（可选）留空则自动转录，或粘贴参考文本提升精度",
    "text_placeholder_required": "粘贴文本内容",
    "text_optional_hint": "✓ 支持纯 ASR 模式，文本留空也可处理",
    "char_count": "当前字符数：{count}",

    "language_select": "语言",
    "lang_cmn": "普通话 🇨🇳",
    "lang_eng": "英语 🇬🇧",
    "lang_jpn": "日语 🇯🇵",
    "lang_kor": "韩语 🇰🇷",
    "lang_yue": "粤语 🇭🇰",

    "processing_mode": "处理模式",
    "mode_mfa_only": "仅标注 (快速)",
    "mode_full": "完整处理 (标注+F0+工程文件)",
    "mode_project_only": "仅生成工程 (WAV + LAB / MIDI)",
    "mode_mfa_only_desc": "只进行自动标注，生成 LAB 文件",
    "mode_full_desc": "执行完整流程：标注 → F0提取 → 工程文件生成",
    "mode_project_only_desc": "直接整合现有 WAV 和 LAB / MIDI 文件生成工程文件，跳过自动标注",

    "output_format": "输出格式",
    "format_sv": "Synthesizer V Studio (.svp)",
    "format_utau": "OpenUtau/UTAU (.ustx)",

    "phoneme_conversion": "音素转换",
    "phoneme_none": "不转换",
    "phoneme_merge": "合并辅音",
    "phoneme_hiragana": "平假名",
    "phoneme_katakana": "片假名",
    "phoneme_none_desc": "保持 LAB 中的原始音素标签不变（适用于所有语言）",
    "phoneme_merge_desc": "将辅音与后续元音合并为罗马字音节（s+a→sa，N→N）",
    "phoneme_hiragana_desc": "合并辅音+元音并转换为平假名（s+a→さ，N→ん）",
    "phoneme_katakana_desc": "合并辅音+元音并转换为片假名（s+a→サ，N→ン）",
    "phoneme_warning": "⚠ 合并/假名转换适用于含逐个音素的日语 LAB 文件（如原始 MFA 输出）",

    "track_name": "音轨名",
    "track_name_placeholder": "输入音轨名",

    "advanced_settings": "⚙️  高级设置",
    "advanced_hide": "⚙️  收起高级设置",
    "bpm": "BPM (节拍/分钟)",
    "base_pitch": "基准音高 (MIDI Note)",
    "pitch_control": "📈  音高精细控制",
    "auto_note_pitch": "自动音符音高",
    "auto_note_pitch_on": "自动对齐实际音高",
    "auto_note_pitch_off": "固定在基准音高",
    "export_pitch_line": "导出连续音高",
    "export_pitch_line_on": "写入 F0 曲线参数",
    "export_pitch_line_off": "仅生成纯净音符",
    "f0_method_section": "F0 提取算法与范围",
    "f0_method": "F0 提取方法",
    "f0_dio": "DIO  (快速)",
    "f0_harvest": "Harvest  (精确)",
    "f0_crepe": "CREPE  (神经网络，抗噪)",
    "f0_rmvpe": "RMVPE  (深度模型，最鲁棒)",
    "crepe_model_size": "CREPE 模型规格",
    "crepe_full": "Full  (精度高)",
    "crepe_tiny": "Tiny  (速度快)",
    "f0_device": "运行设备",
    "precision": "浮点精度",
    "precision_single": "单精度  (Float32)",
    "precision_double": "双精度  (Float64)",
    "f0_smooth": "F0 平滑处理",
    "f0_smooth_window": "平滑窗口大小",
    "f0_floor_hz": "最低频率 (Hz)",
    "f0_ceil_hz": "最高频率 (Hz)",
    "midi_lock_tip": "🔒 从 MIDI 读取",
    "smooth_tip": "推荐值：3-7（越大越平滑）",
    "f0_range_tip": "女声通常 150-300 Hz，男声 80-150 Hz",

    "midi_loaded_banner": "🔒 已导入 MIDI — 以下选项已由 MIDI 数据接管",
    "midi_lock_desc": "🔒 自动音符音高 · BPM · 基准音高 — 将直接从 MIDI 文件中读取",
    "bpm_from_midi": "🔒 {bpm} BPM  (来自 MIDI)",

    "start_processing": "🚀  开始处理",
    "processing_btn": "处理中…  {percent}%",
    "reset": "🔄  重置",
    "system_not_ready_hint": "(系统未就绪或语言模型未下载)",

    "result_title": "✅  处理结果",
    "processing_time": "处理时间: {time}",
    "lab_file_label": "LAB 文件: {name}",
    "project_file_label": "工程文件: {name}",
    "segments_label": "标注段数: {count}",
    "tab_lab_content": "LAB 标注内容",
    "tab_file_info": "文件信息",
    "tab_details": "处理详情",
    "copy_lab": "📋  复制 LAB",
    "download_lab": "📥  下载 LAB",
    "download_project": "📥  下载工程文件",
    "process_next": "🔄  处理下一个",

    "col_stage": "处理阶段",
    "col_status": "状态",
    "col_details": "详情",
    "stage_alignment": "1. 自动标注",
    "stage_f0": "2. F0 音高提取",
    "stage_project": "3. 工程文件生成",
    "status_waiting": "等待",
    "status_running": "进行中",
    "status_done": "完成",
    "status_skipped": "跳过",
    "status_failed": "失败",

    "lab_path_label": "LAB 标注文件:",
    "project_path_label": "工程文件:",
    "output_format_label": "输出格式:",
    "config_label": "处理配置:",
    "cfg_bpm": "BPM: {v}",
    "cfg_base_pitch": "基准音高: {note}  (MIDI {midi})",
    "cfg_auto_pitch": "自动音符音高: {state}",
    "cfg_export_pitch": "导出连续音高: {state}",
    "cfg_f0_method": "F0 方法: {method}",
    "cfg_device": "运行设备: {device}",
    "cfg_precision": "精度: {prec}",
    "state_on": "已启用",
    "state_off": "已禁用",
    "sv_studio": "Synthesizer V Studio",
    "openutau": "OpenUtau / UTAU",

    "system_status": "🔧  系统状态",
    "mfa_status": "MFA 状态:",
    "mfa_installed": "✓ 已安装",
    "mfa_not_installed": "✗ 未安装",
    "mfa_version": "版本:",
    "language_models": "语言模型状态:",
    "processing_modules": "处理模块:",
    "alt_backends_section": "替代对齐后端:",
    "model_cache_dir": "📁 模型缓存目录:",
    "download_btn": "下载",
    "downloading_btn": "下载中…",

    "model_cmn": "CMN  (普通话)",
    "model_eng": "ENG  (英语)",
    "model_jpn": "JPN  (日语)",
    "model_kor": "KOR  (韩语)",
    "model_yue": "YUE  (粤语)",

    "warn_mfa_not_installed": "❌  MFA 未安装",
    "warn_mfa_install_cmd": "pip install montreal-forced-aligner",
    "warn_not_ready_title": "⚠️  警告: 组件未就绪",
    "warn_not_ready_msg": "请下载所需的语言模型或检查系统状态。",
    "warn_install_hint": "然后下载所需的语言模型。",

    "msg_only_one_file": "只能上传一个文件",
    "msg_invalid_lab_type": "只支持 .lab / .mid / .midi 文件",
    "msg_no_lab_content": "没有 LAB 内容可下载",
    "msg_copied": "已复制到剪贴板",
    "msg_copy_failed": "复制失败",
    "msg_model_ok": "模型 '{lang}' 下载成功",
    "msg_model_fail": "模型下载失败: {error}",
    "msg_backend_unreachable": "无法连接到后端",
    "msg_processing_ok": "✅  处理成功！",
    "msg_project_ok": "✅  工程文件生成成功！",
    "msg_status_refreshed": "已刷新系统状态",
    "msg_select_audio": "请选择音频文件",
    "msg_select_lab_midi": "请选择 LAB 或 MIDI 文件",
    "msg_enter_text": "请输入文本（MFA / Qwen3-ForcedAligner 模式需要参考文本）",
    "msg_backend_not_ready": "当前对齐后端未就绪，请检查系统状态",
    "msg_audio_too_large": "音频文件过大（>512MB），建议分割后再处理",
    "msg_lab_downloaded": "LAB 文件已下载: {name}",

    "install_whisperx": "pip install whisperx",
    "install_qwen3": "pip install transformers torch torchaudio accelerate",
    "need_install": "需安装",
    "status_available": "可用",

    "backend_url_label": "后端地址:",
    "backend_url_placeholder": "http://127.0.0.1:5000",
    "connect": "连接",
}
